import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dipesh Shrestha, Nawaraj Luitel, and Aman Chaudhary
 */
public class CAD_Info extends javax.swing.JFrame {

    /**
     * Creates new form CAD_Info
     */
    
    // creating an ArrayList of data type electronicsInfo
    private ArrayList<POJO_Class> list =  new ArrayList<>();
    
    
    public CAD_Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlHead = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductInfo = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAddProduct = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbSearchCategory = new javax.swing.JComboBox<>();
        btnSearchCategory = new javax.swing.JButton();
        btnSearchPrice = new javax.swing.JButton();
        fldSearchPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fldId = new javax.swing.JTextField();
        fldName = new javax.swing.JTextField();
        fldPrice = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        chkOrganization = new javax.swing.JCheckBox();
        chkPerson = new javax.swing.JCheckBox();
        chkNone = new javax.swing.JCheckBox();
        radioLow = new javax.swing.JRadioButton();
        radioMid = new javax.swing.JRadioButton();
        radioHigh = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        manualMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlHead.setBackground(new java.awt.Color(255, 153, 51));

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 3, 30)); // NOI18N
        jLabel10.setText("DNA ELECTRONICS SYSTEM");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Electronic Products Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(204, 0, 51))); // NOI18N

        tblProductInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        tblProductInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "category", "Product Name", "Price", "Recommendation", "Range"
            }
        ));
        jScrollPane1.setViewportView(tblProductInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add-item-icon.png"))); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProductMouseExited(evt);
            }
        });
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnRemoveProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Remove-item-icon.png"))); // NOI18N
        btnRemoveProduct.setText("Remove Product");
        btnRemoveProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoveProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoveProductMouseExited(evt);
            }
        });
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cmbSearchCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Computer", "Smartphone", "TV", "Refrigirator", "Washing machine" }));

        btnSearchCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find-icon.png"))); // NOI18N
        btnSearchCategory.setText("Search By Category");
        btnSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCategoryActionPerformed(evt);
            }
        });

        btnSearchPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iSearch-icon.png"))); // NOI18N
        btnSearchPrice.setText("Search By Price");
        btnSearchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPriceActionPerformed(evt);
            }
        });

        fldSearchPrice.setText("0");
        fldSearchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSearchPriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel7.setText("Select the category");

        jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel8.setText("Enter the price");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/red-search-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(cmbSearchCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fldSearchPrice)
                        .addComponent(btnSearchPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(81, 81, 81)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAddProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnRemoveProduct)
                    .addComponent(btnClear))
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Input", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(204, 0, 51))); // NOI18N

        jLabel1.setText("Product Id");

        jLabel2.setText("Category");

        jLabel3.setText("Product Name");

        jLabel4.setText("Price");

        jLabel5.setText("Recommendation");

        jLabel6.setText("Range");

        fldId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldIdKeyTyped(evt);
            }
        });

        fldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldNameKeyTyped(evt);
            }
        });

        fldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldPriceActionPerformed(evt);
            }
        });
        fldPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldPriceKeyTyped(evt);
            }
        });

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Computer", "Smartphone", "TV", "Refrigirator", "Washing machine" }));

        buttonGroup2.add(chkOrganization);
        chkOrganization.setText("Organizaton");

        buttonGroup2.add(chkPerson);
        chkPerson.setText("Person");

        buttonGroup2.add(chkNone);
        chkNone.setSelected(true);
        chkNone.setText("None");

        buttonGroup1.add(radioLow);
        radioLow.setText("Low");

        buttonGroup1.add(radioMid);
        radioMid.setText("Mid");

        buttonGroup1.add(radioHigh);
        radioHigh.setText("High");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkNone)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radioLow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioMid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioHigh))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fldId)
                        .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fldName)
                        .addComponent(fldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkOrganization)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPerson)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chkOrganization)
                    .addComponent(chkPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(chkNone)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioLow)
                    .addComponent(radioMid)
                    .addComponent(radioHigh))
                .addGap(32, 32, 32))
        );

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-icon.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnExit.setIconTextGap(10);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        menuBar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        menuBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuBarMouseDragged(evt);
            }
        });
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBarMousePressed(evt);
            }
        });

        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        manualMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        manualMenuItem.setText("Manual");
        manualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(manualMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 989, Short.MAX_VALUE)
                .addComponent(btnExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(2, 2, 2)
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    *A method that clears the input fields when triggered
    */
    private void clear(){
        fldId.setText(null);
        cmbCategory.setSelectedIndex(0);
        fldName.setText(null);
        fldPrice.setText(null);
        chkNone.setSelected(true);
        radioMid.setSelected(true);
    }
    
    /*
    *A method that closes the application.
    */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //closes the program when executed:
        int yesOrNo = JOptionPane.showConfirmDialog(rootPane,"Do you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(yesOrNo == 0){
            System.exit(0);
        }        
    }//GEN-LAST:event_btnExitActionPerformed

    //declaring two integer variable which stores the position of the mouse pressed 
    private int xMouse,yMouse;
    /*
    *A method that stores the mouse pressed event to provided variables
    */
    private void menuBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMousePressed
        //these two variable stores the mouse pressed location
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_menuBarMousePressed

    /*
    *A method that set the location of the application when the mouse is dragged
    */
    private void menuBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseDragged
        //getting the location from the screen and setting the application location:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_menuBarMouseDragged

    //a method that calls the clear method to clear the necessary fields when triggered
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    //a method that adds product when triggered
    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        //putting the variables and actions to avoid the exception problems
        try{
            String product_id = fldId.getText().trim();
            String product_category = (String)cmbCategory.getSelectedItem();
            String product_name = fldName.getText();
            int product_price = Integer.parseInt(fldPrice.getText());
            
            if(product_price<5000){
                JOptionPane.showMessageDialog(rootPane,"Minimum price of the product should be 5000","Error!",JOptionPane.ERROR_MESSAGE);
                fldPrice.setText(null);
                return;
            }
            
            String product_recommendation = "None";
            if(chkOrganization.isSelected()){
                product_recommendation = "Organization";
            }
            else if(chkPerson.isSelected()){
                product_recommendation = "Person";
            }

            String product_range;
            if(product_price>4999 && product_price<=30000){
                product_range = "Low";
                radioLow.setSelected(true);
            }
            else if(product_price>30000 && product_price<=70000){
                product_range = "Mid";
                radioMid.setSelected(true);
            }
            else{
                product_range = "High";
                radioHigh.setSelected(true);
            }
            
            if(product_id.isEmpty()||product_category.isEmpty()||product_name.isEmpty()||fldPrice.getText().isEmpty()||product_recommendation.isEmpty()||product_range.isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Please be sure to enter all the required values to further process.","Error!!",JOptionPane.ERROR_MESSAGE);
            }
            else{
                boolean rowEmpty = false;
                if(tblProductInfo.getRowCount()==0){
                    rowEmpty = true;
                }
                else if(tblProductInfo.getRowCount()>0){
                    for(POJO_Class check: list){
                        if(check.getId().equals(product_id)){
                            rowEmpty = false;
                            JOptionPane.showMessageDialog(rootPane,"This product id already exists.","Error!",JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                        else{
                            rowEmpty = true;
                        }
                    }
                }
                if(rowEmpty){
                    DefaultTableModel model = (DefaultTableModel) tblProductInfo.getModel();
                    model.addRow( new Object[]{product_id,product_category,product_name,product_price,product_recommendation,product_range});
                    POJO_Class object = new POJO_Class(product_id,product_category,product_name,product_price,product_recommendation,product_range);
                    list.add(object);
                }
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane,"Please enter a number.","Error!",JOptionPane.ERROR_MESSAGE);
            fldPrice.setText(null);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Please make sure to complete the required information.","Invalid!!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    //a method to change the background color of the exit button 
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
    }//GEN-LAST:event_btnExitMouseEntered

    //a method to change the background color of the exit button 
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnExitMouseExited

    //a method to change the background color of the Add Product button 
    private void btnAddProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseEntered
        btnAddProduct.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAddProductMouseEntered

    //a method to change the background color of the Add Product button
    private void btnAddProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseExited
        btnAddProduct.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnAddProductMouseExited

    //a method to change the background color of the Remove Product button
    private void btnRemoveProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveProductMouseEntered
        btnRemoveProduct.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnRemoveProductMouseEntered

    //a method to change the background color of the Remove Product button
    private void btnRemoveProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveProductMouseExited
        btnRemoveProduct.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnRemoveProductMouseExited

    //a method to change the background color of the Clear button
    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        btnClear.setBackground(new Color(102,193,235));
    }//GEN-LAST:event_btnClearMouseEntered

    //a method to change the background color of the Clear button
    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        btnClear.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnClearMouseExited

    //a method to remove product from the table when triggered
    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductInfo.getModel();
        int select_product = tblProductInfo.getSelectedRow();
        
        try{        
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane,"Please make sure that there is data in the table if not try adding new products.","INVALID",JOptionPane.ERROR_MESSAGE);
            }
            else{
                model.removeRow(select_product);
                list.remove(select_product);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Please select which product to remove.","Error!!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    //a method that closes the application when the exit menu item is pressed
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        int yesOrNo = JOptionPane.showConfirmDialog(rootPane,"Do you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(yesOrNo == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    //a method that clears the table and input fields when new menu item is pressed
    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductInfo.getModel();
        model.setRowCount(0);
        clear();
    }//GEN-LAST:event_newMenuItemActionPerformed

    //a method that searches the products as per the price provided when search button is pressed.
    private void btnSearchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPriceActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductInfo.getModel();
        
        int searchPrice =  Integer.parseInt(fldSearchPrice.getText());
        if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane,"Please add some products first.","Invalid!!!",JOptionPane.ERROR_MESSAGE);
        }
        else{
            SelectionSort.sort(list);
            model.setRowCount(0);
            for(POJO_Class overWrite:list){
                model.addRow(new Object[]{overWrite.getId(),overWrite.getCategory(),overWrite.getName(),overWrite.getPrice(),overWrite.getRecommendation(),overWrite.getRange()});
            }

            int index = binarySearchPrice(list, 0, list.size()-1, searchPrice);
            if(index == -1){
                JOptionPane.showMessageDialog(null,"Search price:- "+searchPrice+ " not found. Please insert correct price.","Invalid Price!",JOptionPane.ERROR_MESSAGE);
            } 
            else{
                POJO_Class data =  list.get(index);
                for(int i=0;i<1;i++){
                    JOptionPane.showMessageDialog(rootPane,"Product ID:- "+ data.getId()+
                            "\n Product Category:- "+ data.getCategory()+
                            "\n Product Name:- "+ data.getName()+
                            "\n Product Price:- "+ data.getPrice()+
                            "\n Product Recommendation:- "+ data.getRecommendation()+
                            "\n Product Range:- "+ data.getRange()
                            ,"Search Result", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSearchPriceActionPerformed

    //a method that opens a file when open menu item is pressed.
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"F:\\IdValidation\\lecture.pdf");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void fldSearchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSearchPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSearchPriceActionPerformed

    //a method that opens a manual file when manual menu item is pressed
    private void manualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualMenuItemActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"F:\\CAD_IS\\src\\Manual\\Manual.pdf");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_manualMenuItemActionPerformed

    //a method that searches for the product belonging to a category when search button is pressed.
    private void btnSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCategoryActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductInfo.getModel();
        
        String search_category = (String) cmbSearchCategory.getSelectedItem();
        ArrayList<POJO_Class> category_list = new ArrayList<>();
        String result="";
        
        if(model.getRowCount()<=0){
            JOptionPane.showMessageDialog(rootPane,"Please make sure that there is at least some products added.","Search Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            for(POJO_Class list_search:list){
                if(list_search.getCategory().equals(search_category)){
                    category_list.add(list_search);
                    result+=list_search.getName()+"\n";
                }
            }
            JOptionPane.showMessageDialog(rootPane,"There seems to be "+category_list.size()+" item belonging to "+search_category+" category."+"\n"+result,"Search Result",JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btnSearchCategoryActionPerformed

    //a method that sets the size limit of the product id.
    private void fldIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldIdKeyTyped
        if(fldId.getText().length()>4){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fldIdKeyTyped

    //a method that sets the size limit of product nepal.
    private void fldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldNameKeyTyped
        if(fldName.getText().length()>20){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fldNameKeyTyped

    /*
    *A method that sets the size limit of product price
    */
    private void fldPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldPriceKeyTyped
        if(fldPrice.getText().length()>6){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fldPriceKeyTyped

    private void fldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPriceActionPerformed

    //a method to find the location of the provided price for searching 
    public static int binarySearchPrice(ArrayList<POJO_Class> search, int low, int high, int value){
        if(low<=high){
            int mid = (low+high)/2;
            if(search.get(mid).getPrice()==value){
                return mid;
            } 
            else if(search.get(mid).getPrice()>value){
                return binarySearchPrice(search,low,mid-1,value);
            }
            else{
                return binarySearchPrice(search,mid+1,high, value);
            }
        }
        else{
            return -1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btnSearchCategory;
    private javax.swing.JButton btnSearchPrice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkNone;
    private javax.swing.JCheckBox chkOrganization;
    private javax.swing.JCheckBox chkPerson;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbSearchCategory;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fldId;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldPrice;
    private javax.swing.JTextField fldSearchPrice;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem manualMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JRadioButton radioHigh;
    private javax.swing.JRadioButton radioLow;
    private javax.swing.JRadioButton radioMid;
    private javax.swing.JTable tblProductInfo;
    // End of variables declaration//GEN-END:variables
}
